### ISSUE TITLE
Support for linear and constant interpolations

### ISSUE THREAD

**Issue by DiThi** [myou-engine/myou-engine#11]
It can be done exporting handles that simulate those scenarios. For constant interpolation, it should be enough with a left handle towards infinity in the X axis, since curves are evaluated from extent to extent and middle portions that exceed extents are ignored.

**Comment by yonicstudios** [comment]
This issue should be solved on commit myou-engine/myou-blender-plugin@5e235af

**Comment by DiThi** [comment]
Yep, that solves the issue, but in the future when making the file format writable we'll want to store the original data and interpolation instead of just the modified curve.
